; Linhas que começam com ";" é apenas um comentário
; Siga os exemplo abaixo:

; Exemplo1: "models/v_awp.mdl" "models/NorToS/v_awp.mdl" // Subistitue para todos no server.


; O Mesmo pode ser feito com sons, Siga um Exemplo:
; "sound/weapons/sound.wav" "sound/weapons/newsound.wav" "CT"

; Você Pode Modificar os Models Abaixo Com Diretorio das Armas que você quer Desativar

"models/v_ak47_.mdl" "models/ABS/v_ak47_ABS.mdl"
;"models/v_awp_ABS.mdl" "models/ARMAS_ABS/v_awp_ABS.mdl"
;"models/v_deagle.mdl" "models/ARMAS_ABS/v_ak47_ABS.mdl"
;"models/v_glock18.mdl" "models/ARMAS_ABS/v_m4a1_ABS.mdl"
;"models/v_m4a1_ABS.mdl" "models/ARMAS_ABS/v_m4a1_ABS.mdl"
;"models/v_usp_ABS.mdl" "models/ARMAS_ABS/v_awp_ABS.mdl"







